# Generated by Django 3.1.1 on 2020-09-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('drama', 'Drama'), ('history', 'History'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('war', 'War')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French'), ('german', 'German'), ('spanish', 'Spanish'), ('hindi', 'Hindi'), ('tamil', 'Tamil')], max_length=50),
        ),
    ]
